# -*- coding: utf-8 -*-
"""Seaborn1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lO9zSOZwiEtI2DUfQALCOCZi27g1dcFi
"""

import seaborn as sns

sns.__version__

import seaborn as sns

data = sns.load_dataset("iris")

sns.lineplot(x="sepal_length",y="sepal_width",data=data)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.get_dataset_names()

t = sns.load_dataset('tips')

t.head()

sns.barplot(x='day',y='total_bill',data=t)

sns.barplot(x='day', y='total_bill',hue='sex',data=t)

sns.color_palette('deep',5)

sns.palplot(sns.color_palette('spring',10))

custom =['red','blue','green']
sns.set_palette(custom)
sns.palplot(sns.color_palette())

sns.barplot(x='total_bill', y='day',data=t)

sns.barplot(x='day',y='total_bill',data=t)

sns.barplot(x='day',y='total_bill',order=['Sun','Fri','Thur','Sat'],data=t)

"""Task-1
Visualization of the flights dataset

i. Load the flights dataset into your notebook

ii.Draw a bar plot of year on the x axis and passengers on the y axis? Which year(s) had more number of passengers?

iii.Draw a bar plot of the month on the x axis and passengers on the y axis? Which month(s) had the most number of passengers and which month(s) had the least number of passengers.

iv. Change the palette of the plot in ii. to winter_r
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

# i. Load the flights dataset into your notebook
f = sns.load_dataset('flights')
f.head()

# ii.Draw a bar plot of year on the x axis and passengers on the y axis? Which year(s) had more number of passengers?
sns.barplot(x="year",y="passengers",data=f)

# iii
sns.barplot(x="month",y="passengers",data=f)

# ii. to winter_r
sns.barplot(x="year",y="passengers",palette='winter_r', data=f)

sns.palplot(sns.color_palette('spring',5))

c = ['red','green','blue','yellow']
sns.set_palette(c)
sns.palplot(sns.color_palette())